---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coverage-processor-sa
  namespace: coverage-processor
  labels:
    app: coverage
    component: processor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coverage-secret-getter
  namespace: coverage-processor
  labels:
    app: coverage
    component: processor
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["triggers.tekton.dev"]
  resources:
  - eventlisteners
  - triggerbindings
  - triggertemplates
  - triggers
  - interceptors
  verbs: ["get", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources:
  - pipelineruns
  - pipelineresources
  - taskruns
  verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coverage-processor-secret-binding
  namespace: coverage-processor
  labels:
    app: coverage
    component: processor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coverage-secret-getter
subjects:
- kind: ServiceAccount
  name: coverage-processor-sa
  namespace: coverage-processor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coverage-clusterinterceptors-reader
  labels:
    app: coverage
    component: processor
rules:
- apiGroups: ["triggers.tekton.dev"]
  resources:
  - clusterinterceptors
  - clustertriggerbindings
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coverage-processor-clusterinterceptors
  labels:
    app: coverage
    component: processor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coverage-clusterinterceptors-reader
subjects:
- kind: ServiceAccount
  name: coverage-processor-sa
  namespace: coverage-processor

